# Generated by Django 2.0.4 on 2018-04-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.IntegerField()),
                ('squares', models.IntegerField()),
                ('cards', models.IntegerField()),
                ('sequence', models.CharField(max_length=100)),
                ('cardList', models.CharField(max_length=1000)),
                ('result', models.CharField(max_length=100)),
            ],
        ),
    ]
